{
 "title": "STSA - Alerts: global",
 "description": "Overall status of one or more swarms",
 "tags": [
  "swarm",
  "traefik",
  "health"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "GLOBAL ALERTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alert if global health % is < 80% over 10m",
   "type": "graph",
   "description": "Global overal health across all layers",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{}) \n          / \n          sum(sts_analyzer_g_total_checks{})\n        ) * 100\n      )\n\n\n",
     "legendFormat": "health %"
    }
   ]
  },
  {
   "title": "Alert if avg global latency is > 1.0s over 10m",
   "type": "graph",
   "description": "For the given timeframe, shows the average response time in seconds/ milliseconds for all service checks executed.",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{}) \n/ \nsum(sts_analyzer_g_total_checks{})",
     "legendFormat": "latency"
    }
   ]
  },
  { "title": "STSA Dashboards", "type": "dashlist", "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "Alert if no latency data received over 10m",
   "type": "graph",
   "description": "Alert if no data is received. For the given timeframe, shows the average response time in seconds/ milliseconds for all service checks executed.",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{}) \n/ \nsum(sts_analyzer_g_total_checks{})",
     "legendFormat": "latency seconds"
    }
   ]
  },
  { "title": "LAYER-0 ALERTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Alert if layer-0 health % < 80% over 10m",
   "type": "graph",
   "description": "Alert if layer-0 health % < 80%",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=\"layer0\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=\"layer0\"})\n        ) * 100\n      )\n\n\n",
     "legendFormat": "health %"
    }
   ]
  },
  {
   "title": "Alert if Layer-0 latency is > 1.5s over 10m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{layer=\"layer0\"}) \n/ \nsum(sts_analyzer_g_total_checks{layer=\"layer0\"})",
     "legendFormat": "latency"
    }
   ]
  },
  { "title": "LAYER-1 ALERTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Alert if layer-1 health % < 80% over 10m",
   "type": "graph",
   "description": "Alert if layer-1 health % < 80%",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=\"layer1\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=\"layer1\"})\n        ) * 100\n      )\n\n\n",
     "legendFormat": "health %"
    }
   ]
  },
  {
   "title": "Alert if Layer-1 latency is > 1.5s over 10m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{layer=\"layer1\"}) \n/ \nsum(sts_analyzer_g_total_checks{layer=\"layer1\"})",
     "legendFormat": "latency"
    }
   ]
  },
  { "title": "LAYER-2 ALERTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Alert if layer-2 health % < 80% over 10m",
   "type": "graph",
   "description": "Alert if layer-2 health % < 80%",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=\"layer2\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=\"layer2\"})\n        ) * 100\n      )\n\n\n",
     "legendFormat": "health %"
    }
   ]
  },
  {
   "title": "Alert if Layer-2 latency is > 1.5s over 10m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{layer=\"layer2\"}) \n/ \nsum(sts_analyzer_g_total_checks{layer=\"layer2\"})",
     "legendFormat": "latency"
    }
   ]
  },
  { "title": "LAYER-3 ALERTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Alert if layer-3 health % < 80% over 10m",
   "type": "graph",
   "description": "Alert if layer-3 health % < 80% over 10m",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=\"layer3\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=\"layer3\"})\n        ) * 100\n      )\n\n\n",
     "legendFormat": "health %"
    }
   ]
  },
  {
   "title": "Alert if Layer-3 latency is > 1.5s over 10m",
   "type": "graph",
   "description": "Alert if Layer-3 latency is > 1.5s over 10m",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{layer=\"layer3\"}) \n/ \nsum(sts_analyzer_g_total_checks{layer=\"layer3\"})",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "LAYER-4 ALERTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true
  },
  {
   "title": "Alert if layer-4 health % < 80% over 10m",
   "type": "graph",
   "description": "Alert if layer-4 health % < 80% over 10m",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=\"layer4\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=\"layer4\"})\n        ) * 100\n      )\n\n\n",
     "legendFormat": "health %"
    }
   ]
  },
  {
   "title": "Alert if Layer-4 latency is > 1.5s over 10m",
   "type": "graph",
   "description": "Alert if Layer-4 latency is > 1.5s over 10m",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{layer=\"layer4\"}) \n/ \nsum(sts_analyzer_g_total_checks{layer=\"layer4\"})",
     "legendFormat": "latency"
    }
   ]
  }
 ]
}