{
 "title": "STSA - Error Inspector",
 "description": "Overall status of one or more swarms",
 "tags": [
  "swarm",
  "traefik",
  "health"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "swarm",
    "query": "label_values(sts_analyzer_g_health_rating, swarm)"
   },
   {
    "name": "context",
    "query": "label_values(sts_analyzer_g_health_rating, context)"
   },
   {
    "name": "formal_name",
    "query": "label_values(sts_analyzer_g_health_rating, formal_name)"
   },
   {
    "name": "layer",
    "query": "label_values(sts_analyzer_g_health_rating, layer)"
   },
   {
    "name": "error",
    "query": "label_values(sts_analyzer_g_attempt_errors, error)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "layer-0",
   "type": "singlestat",
   "description": "failure % of layer0 checks (direct checks via swarm nodes and service published ports). Click for more detail",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": " \n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer0\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer0\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n\n\n"
    }
   ]
  },
  {
   "title": "layer-1",
   "type": "singlestat",
   "description": "failure % of layer1 checks (direct checks via swarm nodes and service published ports). Click for more detail",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": " \n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer1\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer1\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n\n\n"
    }
   ]
  },
  {
   "title": "layer-2",
   "type": "singlestat",
   "description": "failure % of layer2 checks (direct checks via swarm nodes and service published ports). Click for more detail",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": " \n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer2\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer2\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n\n\n"
    }
   ]
  },
  {
   "title": "layer-3",
   "type": "singlestat",
   "description": "failure % of layer3 checks (direct checks via swarm nodes and service published ports). Click for more detail",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": " \n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer3\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer3\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n\n\n"
    }
   ]
  },
  {
   "title": "layer-4",
   "type": "singlestat",
   "description": "failure % of layer4 checks (direct checks via swarm nodes and service published ports). Click for more detail",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": " \n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer4\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer4\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n\n\n"
    }
   ]
  },
  {
   "title": "Attempt Errors & Failed Checks",
   "type": "graph",
   "description": "For the give timeline and selections above, shows the total number of  failed service checks. This also shows the total number of attempts made for every check.",
   "gridPos": { "h": 5, "w": 13, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_failures{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\",layer=~\"$layer\"})",
     "legendFormat": "failed checks"
    },
    {
     "expr": "sum(sts_analyzer_g_attempt_errors{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\",layer=~\"$layer\",error=~\"$error\"})",
     "legendFormat": "attempt errors"
    }
   ]
  },
  {
   "title": "Attempt errors by requested FQDN",
   "type": "graph",
   "description": "Attempt errors by requested FQDN/host for the given timeout",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_attempt_errors{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\",layer=~\"$layer\",error=~\"$error\"}) by (host)"
    }
   ]
  },
  {
   "title": "Attempt errors",
   "type": "table",
   "description": "Shows all failed attempts for the selected timeframe",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_attempt_errors{error=~\"$error\",layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm\",context=~\"$context\"}) by (url,docker_service_name,dns,error,layer)"
    }
   ]
  }
 ]
}