{
 "title": "STSA - Overall Status",
 "description": "Overall status of one or more swarms",
 "tags": [
  "swarm",
  "traefik",
  "health"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "swarm",
    "query": "label_values(sts_analyzer_g_health_rating, swarm)"
   },
   {
    "name": "context",
    "query": "label_values(sts_analyzer_g_health_rating, context)"
   },
   {
    "name": "formal_name",
    "query": "label_values(sts_analyzer_g_health_rating, formal_name)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg. Health %",
   "type": "singlestat",
   "description": "Average overall health for the given timeframe",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "SERVICES",
   "type": "singlestat",
   "description": "Current/latest number of services running on the target swarm that are actively being checked",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_services{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})"
    }
   ]
  },
  {
   "title": "Avg. Fail %",
   "type": "singlestat",
   "description": "Average percentage of service check failures for the given timeframe (after all possible attempts)",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(\n  sum(sts_analyzer_g_failures{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n    / \n\n    sum(sts_analyzer_g_total_checks{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n    \n  ) * 100\n      \n\n\n"
    }
   ]
  },
  {
   "title": "layer-0",
   "type": "singlestat",
   "description": "Average health % of layer0 checks (direct checks via swarm nodes and service published ports). Click for more detail",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer0\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer0\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "layer-1",
   "type": "singlestat",
   "description": "Average health % of layer1 checks (direct checks via swarm nodes via Traefik published ports w/ host-headers). Click for more detail",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer1\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer1\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "layer-2",
   "type": "singlestat",
   "description": "Average health % of layer2 checks (direct checks via int/ext LBs w/ host-headers). Click for more detail",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer2\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer2\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "layer-3",
   "type": "singlestat",
   "description": "Average health % of layer3 checks (checks via standard URLs). Click for more detail",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer3\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer3\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "layer-4",
   "type": "singlestat",
   "description": "Average health % of layer4 checks (direct checks via other app proxies). Click for more detail",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer4\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer4\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "content": "This dashboard shows the overall average state of services runing on the selected Swarm. You can further refine what is show here via dropdowns above\n\nThe data presented here is the result of interrogating the target swarm, marrying its state with service-state.yml files to produce service checks that are executed by \n`servicechecker.py` in the [swarm-traefik-state-analyzer](https://github.com/bitsofinfo/swarm-traefik-state-analyzer) project. \nThis data is then consumed by `servicecheckerdb2prometheus.py` and published to Prometheus and queried by Grafana. \nIf a service is deployed on the swarm and does not have a service-state.yml file with service checks declared, there will be no data here."
  },
  {
   "title": "CONTAINERS",
   "type": "singlestat",
   "description": "Current/latest number of containers/replicas for all services running on the target swarm that are actively being checked",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_replicas{layer=\"layer0\",swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})\n"
    }
   ]
  },
  {
   "title": "Avg. Latency",
   "type": "singlestat",
   "description": "Average response time across all service checks executed in the given timeframe",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n/ \nsum(sts_analyzer_g_total_checks{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})"
    }
   ]
  },
  {
   "title": "CHECKS",
   "type": "singlestat",
   "description": "Current/latest total number of checks against services running on the target swarm",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_checks{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n"
    }
   ]
  },
  {
   "title": "Service Checks Timeline: OK, failed & num. attempts",
   "type": "graph",
   "description": "For the give timeline, across all layers, shows the total number of OK, and failed service checks. This also shows the total number of attempts made for every check. If the total number of attempts is more than the total number of OK+FAILED this can indicate latencies, transient failures, or real long lasting problems etc.",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_ok{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(sts_analyzer_g_failures{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})",
     "legendFormat": "fail"
    },
    {
     "expr": "sum(sts_analyzer_g_attempts{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})",
     "legendFormat": "attempts"
    }
   ]
  },
  { "title": "STSA Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 } },
  {
   "title": "Latency: Average response time",
   "type": "graph",
   "description": "For the given timeframe, shows the average response time in seconds/ milliseconds for all service checks executed.",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"}) \n/ \nsum(sts_analyzer_g_total_checks{swarm=~\"$swarm\",context=~\"$context\",formal_name=~\"$formal_name\"})",
     "legendFormat": "latency seconds"
    }
   ]
  }
 ]
}