{
 "title": "swarm-traefik-state-analyzer - Service Inspector",
 "tags": [
  "health",
  "traefik",
  "swarm"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "docker_service_name",
    "query": "label_values(sts_analyzer_g_health_rating, docker_service_name)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "docker_service_name" },
  {
   "type": "text",
   "description": "This row shows the average state for this service for the given timeframe selected in the time picker. Click to view full details on all layers for this service",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "content": "#### $docker_service_name"
  },
  {
   "title": "Latency",
   "type": "singlestat",
   "description": "Average latency (response time) for all service checks for this service. Click to view service details",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{docker_service_name=~\"$docker_service_name\"}) \n/ \nsum(sts_analyzer_g_total_checks{docker_service_name=~\"$docker_service_name\"})"
    }
   ]
  },
  {
   "title": "layer0",
   "type": "singlestat",
   "description": "Average health for $docker_service_name in layer0",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer0\",docker_service_name=~\"$docker_service_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer0\",docker_service_name=~\"$docker_service_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "layer1",
   "type": "singlestat",
   "description": "Average health for $docker_service_name in layer1",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer1\",docker_service_name=~\"$docker_service_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer1\",docker_service_name=~\"$docker_service_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "layer2",
   "type": "singlestat",
   "description": "Average health for $docker_service_name in layer2",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer2\",docker_service_name=~\"$docker_service_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer2\",docker_service_name=~\"$docker_service_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "layer3",
   "type": "singlestat",
   "description": "Average health for $docker_service_name in layer3",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer3\",docker_service_name=~\"$docker_service_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer3\",docker_service_name=~\"$docker_service_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "layer4",
   "type": "singlestat",
   "description": "Average health for $docker_service_name in layer4",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"layer4\",docker_service_name=~\"$docker_service_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"layer4\",docker_service_name=~\"$docker_service_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  }
 ]
}