{
 "title": "STSA - Layer Inspector",
 "description": "Detailed view across all layers",
 "tags": [
  "health",
  "swarm",
  "traefik"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "docker_service_name",
    "query": "label_values(sts_analyzer_g_health_rating, docker_service_name)"
   },
   {
    "name": "swarm_name",
    "query": "label_values(sts_analyzer_g_health_rating, swarm)"
   },
   {
    "name": "formal_name",
    "query": "label_values(sts_analyzer_g_health_rating, formal_name)"
   },
   {
    "name": "context",
    "query": "label_values(sts_analyzer_g_health_rating, context)"
   },
   {
    "name": "classifier",
    "query": "label_values(sts_analyzer_g_health_rating, classifier)"
   },
   {
    "name": "layer",
    "query": "label_values(sts_analyzer_g_health_rating, layer)"
   },
   {
    "name": "tags",
    "query": "label_values(sts_analyzer_g_health_rating, tags)"
   },
   {
    "name": "version",
    "query": "label_values(sts_analyzer_g_health_rating, version)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "layer" },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "content": "<font size=\"22\"><strong>$layer</strong></font>"
  },
  {
   "title": "$layer Service Checks Timeline: OK, failed & num. attempts",
   "type": "graph",
   "description": "For the give timeline, for $layer, shows the total number of OK, and failed service checks. This also shows the total number of attempts made for every check. If the total number of attempts is more than the total number of OK+FAILED this can indicate latencies, transient failures, or real long lasting problems etc.",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_ok{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(sts_analyzer_g_failures{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})",
     "legendFormat": "fail"
    },
    {
     "expr": "sum(sts_analyzer_g_attempts{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})",
     "legendFormat": "attempts"
    }
   ]
  },
  {
   "title": "Latest Health %",
   "type": "singlestat",
   "description": "$layer latest overall health",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"}) \n          / \n          sum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "Avg. Health %",
   "type": "singlestat",
   "description": "$layer average overall health for the given timeframe for",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (\n        (\n        sum(sts_analyzer_g_failures{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"}) \n          / \n        sum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})\n        ) * 100\n      )\n\n\n"
    }
   ]
  },
  {
   "title": "Latest Fail %",
   "type": "singlestat",
   "description": "$layer latest % of failures",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(sts_analyzer_g_failures{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"}) \n    / \n\n    sum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})\n    \n  ) * 100\n      \n\n\n"
    }
   ]
  },
  {
   "title": "Avg. Fail %",
   "type": "singlestat",
   "description": "for the timeframe selected:  $layer average % of failures",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(\n  sum(sts_analyzer_g_failures{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"}) \n    / \n   sum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})\n  ) * 100\n      \n\n\n"
    }
   ]
  },
  {
   "title": "$layer Latency: Average response time",
   "type": "graph",
   "description": "For the given timeframe, shows the average response time in seconds/ milliseconds for all service checks executed in $layer",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"}) \n/ \nsum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})",
     "legendFormat": "latency seconds"
    }
   ]
  },
  {
   "title": "Latest Latency",
   "type": "singlestat",
   "description": "$layer latest average response time for all checks",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"}) \n/ \nsum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})"
    }
   ]
  },
  {
   "title": "Avg. Latency",
   "type": "singlestat",
   "description": "for the timeframe selected:  $layer average response time for all checks",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_resp_time_seconds{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"}) \n/ \nsum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})"
    }
   ]
  },
  {
   "title": "Latest Retry %",
   "type": "singlestat",
   "description": "$layer latest percentage of all service checks that required further attempts (retries) to either succeed or fail before no more attempts were made.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  abs(\n    sum(sts_analyzer_g_attempts{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})\n      -\n    sum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})\n  ) \n  /\n  sum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})\n) * 100"
    }
   ]
  },
  {
   "title": "Avg Retry %",
   "type": "singlestat",
   "description": "for the timeframe selected: $layer average percentage of all service checks that required further attempts (retries) to either succeed or fail before no more attempts were made.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(\n  abs(\n    sum(sts_analyzer_g_attempts{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})\n      -\n    sum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})\n  ) \n  /\n  sum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"})\n) * 100"
    }
   ]
  },
  {
   "title": "$layer service check failed attempts",
   "type": "table",
   "description": "For the given timeframe, this shows all service checks attempts that failed. One individual attempt failure does not necessarily mean that a subsequent attempt did not succeed.  Causes could be real problems, transient, or misconfiguration etc.",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_attempt_errors{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"}) by (url,docker_service_name,dns,error)"
    }
   ]
  },
  {
   "title": "CONTAINERS",
   "type": "singlestat",
   "description": "Current/latest number of containers/replicas for all services running on the target swarm that are actively being checked",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "  sum(sts_analyzer_g_replicas{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"}) \n"
    }
   ]
  },
  {
   "title": "CHECKS",
   "type": "singlestat",
   "description": "Total number of $layer service checks",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sts_analyzer_g_total_checks{layer=~\"$layer\",formal_name=~\"$formal_name\",swarm=~\"$swarm_name\",context=~\"$context\",classifier=~\"$classifier\",tags=~\"$tags\",version=~\"$version\",docker_service_name=~\"$docker_service_name\"}) \n"
    }
   ]
  }
 ]
}